* response
Thanks a lot! With your help I got it working.

# Solution

I built a new Docker image. The Dockerfile and pip requirements file for it are here:
https://github.com/JeffreyBenjaminBrown/hode6/tree/3f581ecd4cdb30a13c99be2f7ccf8a443ca9cd5d/docker

That uses Ubuntu 23.11, which is the latest image for which the default version of Python is 3.11 (the most recent that the TypeDB driver is compatible with). That compatibility chart you linked to was critical -- otherwise I would have been stumped, not realizing that Python 3.12 is too new.

# What the problem was ... maybe

I had been TypeDB from the Docker image that you provide:
https://hub.docker.com/layers/vaticle/typedb/latest/images/sha256-b62f455c89fb1a31ee7c1ec0af9f2b5ed452a6507b594f7447b5df9f2f92313f

From that image, when I run `pip install typedb-driver` I would get a `can't find it` error:
```
root@26f767b4e868:/opt/typedb-all-linux-x86_64# pip install typedb-driver
ERROR: Could not find a version that satisfies the requirement typedb-driver (from versions: none)
ERROR: No matching distribution found for typedb-driver
root@26f767b4e868:/opt/typedb-all-linux-x86_64#
```

It *might* be because that Docker image uses a four-year-old version of Ubuntu:
```
root@26f767b4e868:/opt/typedb-all-linux-x86_64# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
```

But maybe it was something else.
* first
I asked the TypeDB forum this question today (2024 06 27).

# ##########################
# ##########################

Hello,

I'm making one thread out of these two issues because they seem very related.

Everything described below I discovered by running tweaks of the QuickStart script[1] in an iPython shell from within the TypeDB docker container (called "vaticle/typedb", with image ID 0f332410e5cb, up to date according to DockerHub as of today).

# Some obsolete documentation

The first instruction at the Overview[1] of the Python driver is to run `pip install typedb-driver`. That package is no longer in PyPi, but `typedb-client` is, so I installed the latter.

The QuickStart goes on to suggest some code, starting with `from typedb.driver import TypeDB, SessionType, TransactionType`. That module does not exist, but `typedb.client` does, and those types are all available within it.

Once I replaced every instance of the string "driver" to "client" (the two important targets being the module `typedb.driver` and the object `TypeDB.core_driver`), I was able to execute the script -- which uncovered the second issue.

# Version mismatch

Running that QuickStart code resulted in an error, the money quote from which appears to be the following:
```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "[SRV26] Invalid Server Operation: A protocol version mismat
ch was detected. This server supports version '3' but the driver supports vers
ion '1'. Please use a compatible driver to connect.
```

[1] https://typedb.com/docs/drivers/python/overview
